services:
  frontend:
    build: ./web/frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./web/backend
    ports:
      - "3000:3000"
    environment:
      - DB_URL=postgres://admin:password@db:5432/app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d  # SQL-инициализация
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  redis:
    image: redis:7

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
